+incdir+${SOCBLOX}/units/ethmac
${SOCBLOX}/units/ethmac/eth_clockgen.v
${SOCBLOX}/units/ethmac/eth_cop.v
${SOCBLOX}/units/ethmac/eth_crc.v
${SOCBLOX}/units/ethmac/eth_fifo.v
${SOCBLOX}/units/ethmac/eth_maccontrol.v
${SOCBLOX}/units/ethmac/eth_macstatus.v
${SOCBLOX}/units/ethmac/eth_miim.v
${SOCBLOX}/units/ethmac/eth_outputcontrol.v
${SOCBLOX}/units/ethmac/eth_random.v
${SOCBLOX}/units/ethmac/eth_register.v
${SOCBLOX}/units/ethmac/eth_registers.v
${SOCBLOX}/units/ethmac/eth_rxaddrcheck.v
${SOCBLOX}/units/ethmac/eth_rxcounters.v
${SOCBLOX}/units/ethmac/eth_rxethmac.v
${SOCBLOX}/units/ethmac/eth_rxstatem.v
${SOCBLOX}/units/ethmac/eth_shiftreg.v
${SOCBLOX}/units/ethmac/eth_spram_256x32.v
${SOCBLOX}/units/ethmac/eth_transmitcontrol.v
${SOCBLOX}/units/ethmac/eth_txcounters.v
${SOCBLOX}/units/ethmac/eth_txethmac.v
${SOCBLOX}/units/ethmac/eth_txstatem.v
${SOCBLOX}/units/ethmac/eth_wishbone.v
${SOCBLOX}/units/ethmac/eth_top.sv