
${UNITS}/interconnects/wb/wb_interconnect_NxN.sv
${UNITS}/interconnects/wb/wb_interconnect_1x1.sv
${UNITS}/interconnects/wb/wb_interconnect_1x1_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_1x2.sv
${UNITS}/interconnects/wb/wb_interconnect_1x2_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_1x3.sv
${UNITS}/interconnects/wb/wb_interconnect_1x3_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_1x4.sv
${UNITS}/interconnects/wb/wb_interconnect_1x4_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_2x1.sv
${UNITS}/interconnects/wb/wb_interconnect_2x1_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_2x2.sv
${UNITS}/interconnects/wb/wb_interconnect_2x2_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_2x3.sv
${UNITS}/interconnects/wb/wb_interconnect_2x3_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_2x4.sv
${UNITS}/interconnects/wb/wb_interconnect_2x4_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_3x1.sv
${UNITS}/interconnects/wb/wb_interconnect_3x1_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_3x2.sv
${UNITS}/interconnects/wb/wb_interconnect_3x2_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_3x3.sv
${UNITS}/interconnects/wb/wb_interconnect_3x3_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_3x4.sv
${UNITS}/interconnects/wb/wb_interconnect_3x4_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_4x1.sv
${UNITS}/interconnects/wb/wb_interconnect_4x1_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_4x2.sv
${UNITS}/interconnects/wb/wb_interconnect_4x2_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_4x3.sv
${UNITS}/interconnects/wb/wb_interconnect_4x3_pt.sv
${UNITS}/interconnects/wb/wb_interconnect_4x4.sv
${UNITS}/interconnects/wb/wb_interconnect_4x4_pt.sv
