
COMMON_SVM_DIR=$(SOCBLOX)/common/svm

COMMON_SVM_SRC=\
	svm_elf_loader.cpp
	
COMMON_SVM_OBJS=$(foreach o,$(COMMON_SVM_SRC:.cpp=.o),$(SOCBLOX_OBJDIR)/$(o))

COMMON_SVM_LINK=-lcommon_svm

COMMON_SVM_LIB=$(SOCBLOX_LIBDIR)/$(LIBPREF)common_svm$(DLLEXT)

LIB_TARGETS += $(COMMON_SVM_LIB)

CXXFLAGS += -I$(COMMON_SVM_DIR)

